export type MockServerData = {
  titles: string[];
  descriptions: string[];
  previewImages: string[];
  roomImages: string[];
  users: string[];
  emails: string[];
  avatars: string[];
  publicationDates: string[];
  cities: string[];
  isPremium: boolean[];
  isFavorite: boolean[];
  ratings: number[];
  apartmentTypes: string[];
  roomAmounts: number[];
  guestAmounts: number[];
  rentalCosts: number[];
  facilities: string[][];
  commentsAmounts: number[];
  locations: { latitude: number; longitude: number }[];
};
