
# Получить детальную инфу для объявления по идентификатору РАБОТАЕТ TO DO: комментарии
GET http://localhost:5000/offers/65e0def949327b5bf45d2ad4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTE1ODU2MiwiZXhwIjoxNzA5MzMxMzYyfQ.DjebHp8MFJRIZ0MxqQRULcavTKxeyT0T7bBacijGFTg


###

## Получить список объявлений РАБОТАЕТ, TO DO: комментарии
GET http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTE1ODU2MiwiZXhwIjoxNzA5MzMxMzYyfQ.DjebHp8MFJRIZ0MxqQRULcavTKxeyT0T7bBacijGFTg


###

## создать объявление РАБОТАЕТ
POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTE1ODU2MiwiZXhwIjoxNzA5MzMxMzYyfQ.DjebHp8MFJRIZ0MxqQRULcavTKxeyT0T7bBacijGFTg
Content-Type: application/json

{
  "title": "Offer for deleting",
  "description": "Large villa near see. Mountin view",
  "publicationDate": "2023-09-06T08:45:40.283Z",
  "city": "Paris",
  "previewImage":  "http://preview_image.jpg",
  "housingPhotos": [
      "http://photo1.jpg",
      "http://photo1.jpg",
      "http://photo1.jpg",
      "http://photo1.jpg",
      "http://photo1.jpg",
      "http://photo1.jpg"
  ],
  "premium": false,
  "apartmentType": "Villa",
  "roomAmount": 4,
  "guestAmount": 2,
  "rentalCost": 1000,
  "facilities": ["Washer"],
  "authorId": "65d9c585ce3dbe7f17ad61c2",
  "location": {
    "latitude": 49.657097,
    "longitude": 8.048281
  }
}

###

## Удалить объявление по идентификатору РАБОТАЕТ

DELETE http://localhost:5000/offers/65e0f68f016207473cc7ba51 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTI0MjMyNiwiZXhwIjoxNzA5NDE1MTI2fQ.O8tgyBdwbWUse3kFaBH4TQkJvYzmEcmt6hZ82a08pD0

###

## Редактировать объявление  РАБОТАЕТ TO DO добавить комменты

PATCH http://localhost:5000/offers/65db15b81abcb6791779a1ee HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwODg1NjYyNywiZXhwIjoxNzA5MDI5NDI3fQ.sPPW4Z_CjzZGxF83u8n4fBShC3Ypc8BxajHBfmRqAL0
Content-Type: application/json

{
  "title": "Modern villa in near see for Mary. Updated again 3333",
  "rentalCost": 1500,
  "apartmentType": "House"
}

###

## Список комментариев к объявлению РАБОТАЕТ
GET http://localhost:5000/offers/65db15b81abcb6791779a1ee/comments HTTP/1.1

###

## Список избранных РАБОТАЕТ TO DO добавить комменты 

GET http://localhost:5000/offers/favorites
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayIsImlkIjoiNjVkOWM1ODVjZTNkYmU3ZjE3YWQ2MWMyIiwiaWF0IjoxNzA4Nzc2ODQzLCJleHAiOjE3MDg5NDk2NDN9.9ZP8nH0pJqXSIicJjmWBlD8c1mUjHhfYbMilWWOaLio
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwODg4MDUzMywiZXhwIjoxNzA5MDUzMzMzfQ.j4sDavmwhol40ahfnL0t2xXyVe5U_C29XaFlL_EFclE

###

## Список премиальных  РАБОТАЕТ  TO DO добавить комменты
GET http://localhost:5000/offers/premium?city=Paris

###

## Добавление/удаление предложения в/из избранное.

PUT http://localhost:5000/offers/65e0def949327b5bf45d2ad4/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTE1ODU2MiwiZXhwIjoxNzA5MzMxMzYyfQ.DjebHp8MFJRIZ0MxqQRULcavTKxeyT0T7bBacijGFTg
Content-Type: application/json

{
  "favorites": true
}

###

## Загрузить изображение для объявления
POST http://localhost:5000/offers/65db15b81abcb6791779a1ee/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwOTE1ODU2MiwiZXhwIjoxNzA5MzMxMzYyfQ.DjebHp8MFJRIZ0MxqQRULcavTKxeyT0T7bBacijGFTg
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="paris.png"
Content-Type: image/png

< /Users/marianna/Desktop/paris.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

###