# Комментарии
## Создать комментарий РАБОТАЕТ

POST http://localhost:5000/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcnlAZ21haWwubmV0IiwibmFtZSI6Ik1hcnkiLCJpZCI6IjY1ZGIxNTExMWFiY2I2NzkxNzc5YTFlNSIsImlhdCI6MTcwODg1NjYyNywiZXhwIjoxNzA5MDI5NDI3fQ.sPPW4Z_CjzZGxF83u8n4fBShC3Ypc8BxajHBfmRqAL0
Content-Type: application/json

{
  "text": "Комментарий к предложению",
  "offerId": "65db15b81abcb6791779a1ee",
  "rating": 4
}

###